### ISSUE TITLE
social_media not works for me (in zola serve)

### ISSUE THREAD

**Issue by whoizit** [oltd/dose#5]
idk why
```sh
~/project/blog > rustc -V
rustc 1.58.1 (Arch Linux rust 1:1.58.1-1)
~/project/blog > zola -V
zola 0.15.3
```
```toml
# config.toml
# ...
[extra]  
social_media = [  
    {name = "GitHub", url = "https://github.com/whoizit"},  
    {name = "Mastodon", url = "https://qoto.org/@whoami"},  
]  
```
```
~/project/blog > cat content/_index.md
title = "List of blog posts"
sort_by = "date"
template = "index.html"
page_template = "page.html"
+++
```
![image](https://user-images.githubusercontent.com/359276/150903094-3bb42bd8-12bd-4ab3-a127-984800876430.png)
